### ISSUE TITLE
why don't integrate with nebula-studio

### ISSUE THREAD

**Issue by loveJasmine** [vesoft-inc/nebulagraph-veditor#11]
It looks there are something in common

**Comment by wey-gu** [comment]
This project is a js lib created when the team was creating [nebulagraph explorer](https://nebula-graph.com.cn/products/explorer/) :), it's actually an enhanced nebulagraph studio :D, but not a community offering project for now.

**Comment by mizy** [comment]
> It looks there are something in common

VEditor is a  js graph lib,so you can  build any kind of app with it, and also you have to code to use it
