### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by loveJasmine** [vesoft-inc/nebulagraph-veditor#12]
PS C:\vesoft-inc\nebulagraph-veditor> npm run build

> @vesoft-inc/veditor@4.2.0 build
> webpack --config webpack.config.build.js

CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @vesoft-inc/veditor@4.2.0
npm ERR! Found: webpack@5.74.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.71.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from css-loader@1.0.1
npm ERR! node_modules/css-loader
npm ERR!   dev css-loader@"^1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by wey-gu** [comment]
have you done npm install first?

**Comment by loveJasmine** [comment]
PS C:\vesoft-inc\nebulagraph-veditor> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @vesoft-inc/veditor@4.2.0
npm ERR! Found: webpack@5.74.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.71.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from css-loader@1.0.1
npm ERR! node_modules/css-loader
npm ERR!   dev css-loader@"^1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by loveJasmine** [comment]
after
 npm install --force 

it works
